INFO     mypy.lib.playwright.publish_config:publish_config.py:119 🟢 -----> 配置如下 <-----
INFO     mypy.apps.ppt2douyin.main:main.py:20 🟢 ============================================================
INFO     mypy.apps.ppt2douyin.main:main.py:21 🟢 正在把当前目录下的 pptx 转成 image_article
INFO     mypy.apps.ppt2douyin.main:main.py:22 🟢 ============================================================
INFO     mypy.apps.ppt2douyin.ppt2video:ppt2video.py:118 🟢 开始转换《/home/runner/work/Python/Python/mypy/tests/apps/ppt2douyin/消化内科护士长竞聘.pptx》
INFO     mypy.lib.ppt.ppt_handler:ppt_handler.py:59 🟢 通过 libreoffice 把 PPT 转成 PDF，再通过 pdf2image 库转成图片，输出到: /tmp/tmptgbuwdbl
DEBUG    /home/runner/work/Python/Python/mypy/utils/tools.py:tools.py:235 🔵 正在执行命令: ['libreoffice', '--headless', '--convert-to', 'pdf', '--outdir', '/tmp/tmptgbuwdbl', '/home/runner/work/Python/Python/mypy/tests/apps/ppt2douyin/消化内科护士长竞聘.pptx']
ERROR    mypy.apps.ppt2douyin.ppt2video:ppt2video.py:102 🔴 PPT 格式转换异常: [Errno 2] No such file or directory: '/home/runner/work/Python/Python/mypy/tests/apps/ppt2douyin/消化内科护士长竞聘.pdf'
Traceback (most recent call last):
  File "/home/runner/work/Python/Python/mypy/apps/ppt2douyin/ppt2video.py", line 100, in _ppt_trans
    self._ppt_handler(ppt_path, output_path)
  File "/home/runner/work/Python/Python/mypy/apps/ppt2douyin/ppt2video.py", line 49, in ppt2image_group
    ppt2image(ppt_path, tmp_output_dir)
  File "/home/runner/work/Python/Python/mypy/lib/ppt/ppt_handler.py", line 67, in ppt2image
    pdf_handler.pdf2image(image_dir=output_path,
  File "/home/runner/work/Python/Python/mypy/lib/pdf/pdf_handler.py", line 60, in pdf2image
    shutil.copy2(self._input_pdf_path, tmp_filename)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Python/Python/mypy/tests/apps/ppt2douyin/消化内科护士长竞聘.pdf'
ERROR    mypy.apps.ppt2douyin.main:main.py:34 🔴 [Errno 2] No such file or directory: '/home/runner/work/Python/Python/mypy/tests/apps/ppt2douyin/消化内科护士长竞聘.pdf'
Traceback (most recent call last):
  File "/home/runner/work/Python/Python/mypy/apps/ppt2douyin/main.py", line 23, in main
    ppt_transfer.batch_ppt2transfer()
  File "/home/runner/work/Python/Python/mypy/apps/ppt2douyin/ppt2video.py", line 119, in batch_ppt2transfer
    self._ppt_trans(ppt_file)
  File "/home/runner/work/Python/Python/mypy/apps/ppt2douyin/ppt2video.py", line 103, in _ppt_trans
    raise ex
  File "/home/runner/work/Python/Python/mypy/apps/ppt2douyin/ppt2video.py", line 100, in _ppt_trans
    self._ppt_handler(ppt_path, output_path)
  File "/home/runner/work/Python/Python/mypy/apps/ppt2douyin/ppt2video.py", line 49, in ppt2image_group
    ppt2image(ppt_path, tmp_output_dir)
  File "/home/runner/work/Python/Python/mypy/lib/ppt/ppt_handler.py", line 67, in ppt2image
    pdf_handler.pdf2image(image_dir=output_path,
  File "/home/runner/work/Python/Python/mypy/lib/pdf/pdf_handler.py", line 60, in pdf2image
    shutil.copy2(self._input_pdf_path, tmp_filename)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Python/Python/mypy/tests/apps/ppt2douyin/消化内科护士长竞聘.pdf'