DEBUG    /home/runner/work/github-runner/github-runner/mypy/utils/tools.py:tools.py:178 ðŸ”µ func start at: 1724809503.0921648
WARNING  /home/runner/work/github-runner/github-runner/mypy/utils/tools.py:tools.py:181 ðŸŸ  func exception: <class 'Exception'> at 1724809503.092327
DEBUG    /home/runner/work/github-runner/github-runner/mypy/utils/tools.py:tools.py:178 ðŸ”µ func start at: 1724809504.0935426
WARNING  /home/runner/work/github-runner/github-runner/mypy/utils/tools.py:tools.py:181 ðŸŸ  func exception: <class 'Exception'> at 1724809504.093934