INFO     mypy.lib.playwright.publish_config:publish_config.py:117 🟢 -----> 配置如下 <-----
INFO     mypy.lib.douyin.publish_app:publish_app.py:130 🟢 正在使用 [cookie_17688150852.json] 发布作品，当前账号排序: [1]
INFO     mypy.lib.douyin.publish_app:publish_helper.py:109 🟢 ============================================================
INFO     mypy.lib.douyin.publish_app:publish_helper.py:110 🟢 [DouyinImagesPublishHelper] 开始执行发布任务
INFO     mypy.lib.douyin.publish_app:publish_helper.py:111 🟢 ============================================================
INFO     mypy.lib.douyin.publish_app:publish_helper.py:74 🟢 当前登录账号为 [埃斯顿非更]
ERROR    mypy.lib.douyin.publish_app:publish_helper.py:347 🔴 发生异常: Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 341, in upload
    await page.click(upload_locator)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 60, in __aexit__
    await self._event.value
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================

Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 341, in upload
    await page.click(upload_locator)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 60, in __aexit__
    await self._event.value
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================
ERROR    mypy.lib.douyin.publish_app:publish_helper.py:130 🔴 ❌❌❌《ppt_slide_images》发布异常: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 122, in publish_mission
    await self.upload(page)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/image_publish_helper.py", line 47, in upload
    await super().upload(page, upload_url, upload_locator, upload_filepath)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 348, in upload
    raise ex
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 341, in upload
    await page.click(upload_locator)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 60, in __aexit__
    await self._event.value
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================
WARNING  mypy.lib.douyin.publish_app:before_sleep.py:65 Retrying <unknown> in 3.0 seconds as it raised PublishFail: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================.
INFO     mypy.lib.douyin.publish_app:publish_helper.py:109 🟢 ============================================================
INFO     mypy.lib.douyin.publish_app:publish_helper.py:110 🟢 [DouyinImagesPublishHelper] 开始执行发布任务
INFO     mypy.lib.douyin.publish_app:publish_helper.py:111 🟢 ============================================================
INFO     mypy.lib.douyin.publish_app:publish_helper.py:74 🟢 当前登录账号为 [埃斯顿非更]
ERROR    mypy.lib.douyin.publish_app:publish_helper.py:347 🔴 发生异常: Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 341, in upload
    await page.click(upload_locator)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 60, in __aexit__
    await self._event.value
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================

Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 341, in upload
    await page.click(upload_locator)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 60, in __aexit__
    await self._event.value
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================
ERROR    mypy.lib.douyin.publish_app:publish_helper.py:130 🔴 ❌❌❌《ppt_slide_images》发布异常: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 122, in publish_mission
    await self.upload(page)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/image_publish_helper.py", line 47, in upload
    await super().upload(page, upload_url, upload_locator, upload_filepath)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 348, in upload
    raise ex
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 341, in upload
    await page.click(upload_locator)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 60, in __aexit__
    await self._event.value
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================
WARNING  mypy.lib.douyin.publish_app:before_sleep.py:65 Retrying <unknown> in 3.0 seconds as it raised PublishFail: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================.
INFO     mypy.lib.douyin.publish_app:publish_helper.py:109 🟢 ============================================================
INFO     mypy.lib.douyin.publish_app:publish_helper.py:110 🟢 [DouyinImagesPublishHelper] 开始执行发布任务
INFO     mypy.lib.douyin.publish_app:publish_helper.py:111 🟢 ============================================================
INFO     mypy.lib.douyin.publish_app:publish_helper.py:74 🟢 当前登录账号为 [埃斯顿非更]
ERROR    mypy.lib.douyin.publish_app:publish_helper.py:347 🔴 发生异常: Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 341, in upload
    await page.click(upload_locator)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 60, in __aexit__
    await self._event.value
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================

Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 341, in upload
    await page.click(upload_locator)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 60, in __aexit__
    await self._event.value
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================
ERROR    mypy.lib.douyin.publish_app:publish_helper.py:130 🔴 ❌❌❌《ppt_slide_images》发布异常: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 122, in publish_mission
    await self.upload(page)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/image_publish_helper.py", line 47, in upload
    await super().upload(page, upload_url, upload_locator, upload_filepath)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 348, in upload
    raise ex
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 341, in upload
    await page.click(upload_locator)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 60, in __aexit__
    await self._event.value
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================
ERROR    mypy.lib.douyin.publish_app:publish_helper.py:151 🔴 ❌❌❌《ppt_slide_images》发布异常: RetryError[<Future at 0x7f3dcdad7130 state=finished raised PublishFail>]
Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 122, in publish_mission
    await self.upload(page)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/image_publish_helper.py", line 47, in upload
    await super().upload(page, upload_url, upload_locator, upload_filepath)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 348, in upload
    raise ex
  File "/home/runner/work/github-runner/github-runner/mypy/lib/douyin/publish_helper.py", line 341, in upload
    await page.click(upload_locator)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 60, in __aexit__
    await self._event.value
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/playwright/_impl/_async_base.py", line 35, in value
    return mapping.from_maybe_impl(await self._future)
playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 149, in do_publish
    await self.publish_mission(playwright)
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 132, in publish_mission
    raise PublishFail(original_exception=ex) from ex
mypy.lib.playwright.exceptions.PublishFail: Timeout 120000ms exceeded while waiting for event "filechooser"
=========================== logs ===========================
waiting for event "filechooser"
============================================================

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/github-runner/github-runner/mypy/lib/playwright/publish_helper.py", line 143, in do_publish
    async for attempt in AsyncRetrying(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_asyncio.py", line 123, in __anext__
    do = await self.iter(retry_state=self._retry_state)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_asyncio.py", line 110, in iter
    result = await action(retry_state)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/_asyncio.py", line 78, in inner
    return fn(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py", line 411, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f3dcdad7130 state=finished raised PublishFail>]