{"uid":"27b666c6408c0bdb","name":"test_y2_downloader[video]","fullName":"lib.youtube.test_y2_downloader#test_y2_downloader","historyId":"d1a0b4889c40e956ba730446cbb448e5","time":{"start":1724809389516,"stop":1724809427441,"duration":37925},"description":"\n    测试 youtu 下载工具\n    ","descriptionHtml":"<pre><code>测试 youtu 下载工具\n</code></pre>\n","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7f38502f31c0 state=finished raised PytubeError>]","statusTrace":"self = <pytube.__main__.YouTube object: videoId=0AVrZ5tw_SM>\n\n    @property\n    def title(self) -> str:\n        \"\"\"Get the video title.\n    \n        :rtype: str\n        \"\"\"\n        if self._title:\n            return self._title\n    \n        try:\n>           self._title = self.vid_info['videoDetails']['title']\nE           KeyError: 'videoDetails'\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pytube/__main__.py:341: KeyError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Retrying object at 0x7f385055fcd0 (stop=<tenacity.stop.stop_after_attempt object at 0x7f3851f56ca0>, wait=<tenacity.w...0x7f38806fe310>, before=<function before_nothing at 0x7f388098c940>, after=<function after_nothing at 0x7f388098cca0>)>\nfn = <function Y2Downloader.download_video at 0x7f3851f5f160>\nargs = (<mypy.lib.youtube.y2_downloader.Y2Downloader object at 0x7f385055fe80>, 'https://www.youtube.com/watch?v=0AVrZ5tw_SM')\nkwargs = {}\nretry_state = <RetryCallState 139879842707248: attempt #5; slept for 36.0; last result: failed (PytubeError Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube)>\ndo = <tenacity.DoAttempt object at 0x7f3848e74880>\n\n    def __call__(\n        self,\n        fn: t.Callable[..., WrappedFnReturnT],\n        *args: t.Any,\n        **kwargs: t.Any,\n    ) -> WrappedFnReturnT:\n        self.begin()\n    \n        retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)\n        while True:\n            do = self.iter(retry_state=retry_state)\n            if isinstance(do, DoAttempt):\n                try:\n>                   result = fn(*args, **kwargs)\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:478: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/youtube/y2_downloader.py:183: in download_video\n    raise ex\nmypy/lib/youtube/y2_downloader.py:153: in download_video\n    api = Y2VideoHandler(work_path=self._work_path,\nmypy/lib/youtube/y2_video_handler.py:239: in __init__\n    self._video_original_title = y2_video.title\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pytube.__main__.YouTube object: videoId=0AVrZ5tw_SM>\n\n    @property\n    def title(self) -> str:\n        \"\"\"Get the video title.\n    \n        :rtype: str\n        \"\"\"\n        if self._title:\n            return self._title\n    \n        try:\n            self._title = self.vid_info['videoDetails']['title']\n        except KeyError:\n            # Check_availability will raise the correct exception in most cases\n            #  if it doesn't, ask for a report.\n            self.check_availability()\n>           raise exceptions.PytubeError(\n                (\n                    f'Exception while accessing title of {self.watch_url}. '\n                    'Please file a bug report at https://github.com/pytube/pytube'\n                )\n            )\nE           pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pytube/__main__.py:346: PytubeError\n\nThe above exception was the direct cause of the following exception:\n\ntest_output_dir = '/home/runner/work/github-runner/github-runner/mypy/tests/lib/youtube/_out/test_y2_downloader'\nurl = 'https://www.youtube.com/watch?v=0AVrZ5tw_SM'\n\n    @pytest.mark.parametrize(\"url\", [\n        \"https://www.youtube.com/watch?v=0AVrZ5tw_SM\",\n        \"https://www.youtube.com/playlist?list=PL-CDIidnoXnBqgBVbf5y9Qm4y4ZKHHYUS\",\n        \"https://www.youtube.com/channel/UC4cw8Y12uIvrh8eLwGA3n8A\"],\n        ids=['video', 'playlist', 'channel'])\n    def test_y2_downloader(test_output_dir, url):\n        \"\"\"\n        测试 youtu 下载工具\n        \"\"\"\n        api = Y2Downloader(work_path=test_output_dir, url=url)\n>       api.do_download()\n\nmypy/tests/lib/youtube/test_y2_downloader.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/youtube/y2_downloader.py:280: in do_download\n    download_filepath, _, _, _ = self.download_video(self._url)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:336: in wrapped_f\n    return copy(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:475: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:376: in iter\n    result = action(retry_state)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nrs = <RetryCallState 139879842707248: attempt #5; slept for 36.0; last result: failed (PytubeError Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube)>\n\n    def exc_check(rs: \"RetryCallState\") -> None:\n        fut = t.cast(Future, rs.outcome)\n        retry_exc = self.retry_error_cls(fut)\n        if self.reraise:\n            raise retry_exc.reraise()\n>       raise retry_exc from fut.exception()\nE       tenacity.RetryError: RetryError[<Future at 0x7f38502f31c0 state=finished raised PytubeError>]\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:419: RetryError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop_policy","time":{"start":1724804131376,"stop":1724804131376,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"copy_config_to_dir","time":{"start":1724809389513,"stop":1724809389515,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"test_output_dir","time":{"start":1724809389515,"stop":1724809389516,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"\n    测试 youtu 下载工具\n    ","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7f38502f31c0 state=finished raised PytubeError>]","statusTrace":"self = <pytube.__main__.YouTube object: videoId=0AVrZ5tw_SM>\n\n    @property\n    def title(self) -> str:\n        \"\"\"Get the video title.\n    \n        :rtype: str\n        \"\"\"\n        if self._title:\n            return self._title\n    \n        try:\n>           self._title = self.vid_info['videoDetails']['title']\nE           KeyError: 'videoDetails'\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pytube/__main__.py:341: KeyError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Retrying object at 0x7f385055fcd0 (stop=<tenacity.stop.stop_after_attempt object at 0x7f3851f56ca0>, wait=<tenacity.w...0x7f38806fe310>, before=<function before_nothing at 0x7f388098c940>, after=<function after_nothing at 0x7f388098cca0>)>\nfn = <function Y2Downloader.download_video at 0x7f3851f5f160>\nargs = (<mypy.lib.youtube.y2_downloader.Y2Downloader object at 0x7f385055fe80>, 'https://www.youtube.com/watch?v=0AVrZ5tw_SM')\nkwargs = {}\nretry_state = <RetryCallState 139879842707248: attempt #5; slept for 36.0; last result: failed (PytubeError Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube)>\ndo = <tenacity.DoAttempt object at 0x7f3848e74880>\n\n    def __call__(\n        self,\n        fn: t.Callable[..., WrappedFnReturnT],\n        *args: t.Any,\n        **kwargs: t.Any,\n    ) -> WrappedFnReturnT:\n        self.begin()\n    \n        retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)\n        while True:\n            do = self.iter(retry_state=retry_state)\n            if isinstance(do, DoAttempt):\n                try:\n>                   result = fn(*args, **kwargs)\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:478: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/youtube/y2_downloader.py:183: in download_video\n    raise ex\nmypy/lib/youtube/y2_downloader.py:153: in download_video\n    api = Y2VideoHandler(work_path=self._work_path,\nmypy/lib/youtube/y2_video_handler.py:239: in __init__\n    self._video_original_title = y2_video.title\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pytube.__main__.YouTube object: videoId=0AVrZ5tw_SM>\n\n    @property\n    def title(self) -> str:\n        \"\"\"Get the video title.\n    \n        :rtype: str\n        \"\"\"\n        if self._title:\n            return self._title\n    \n        try:\n            self._title = self.vid_info['videoDetails']['title']\n        except KeyError:\n            # Check_availability will raise the correct exception in most cases\n            #  if it doesn't, ask for a report.\n            self.check_availability()\n>           raise exceptions.PytubeError(\n                (\n                    f'Exception while accessing title of {self.watch_url}. '\n                    'Please file a bug report at https://github.com/pytube/pytube'\n                )\n            )\nE           pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/pytube/__main__.py:346: PytubeError\n\nThe above exception was the direct cause of the following exception:\n\ntest_output_dir = '/home/runner/work/github-runner/github-runner/mypy/tests/lib/youtube/_out/test_y2_downloader'\nurl = 'https://www.youtube.com/watch?v=0AVrZ5tw_SM'\n\n    @pytest.mark.parametrize(\"url\", [\n        \"https://www.youtube.com/watch?v=0AVrZ5tw_SM\",\n        \"https://www.youtube.com/playlist?list=PL-CDIidnoXnBqgBVbf5y9Qm4y4ZKHHYUS\",\n        \"https://www.youtube.com/channel/UC4cw8Y12uIvrh8eLwGA3n8A\"],\n        ids=['video', 'playlist', 'channel'])\n    def test_y2_downloader(test_output_dir, url):\n        \"\"\"\n        测试 youtu 下载工具\n        \"\"\"\n        api = Y2Downloader(work_path=test_output_dir, url=url)\n>       api.do_download()\n\nmypy/tests/lib/youtube/test_y2_downloader.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/youtube/y2_downloader.py:280: in do_download\n    download_filepath, _, _, _ = self.download_video(self._url)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:336: in wrapped_f\n    return copy(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:475: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:376: in iter\n    result = action(retry_state)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nrs = <RetryCallState 139879842707248: attempt #5; slept for 36.0; last result: failed (PytubeError Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube)>\n\n    def exc_check(rs: \"RetryCallState\") -> None:\n        fut = t.cast(Future, rs.outcome)\n        retry_exc = self.retry_error_cls(fut)\n        if self.reraise:\n            raise retry_exc.reraise()\n>       raise retry_exc from fut.exception()\nE       tenacity.RetryError: RetryError[<Future at 0x7f38502f31c0 state=finished raised PytubeError>]\n\n/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/tenacity/__init__.py:419: RetryError","steps":[],"attachments":[{"uid":"6c141bf652351f9e","name":"log","source":"6c141bf652351f9e.txt","type":"text/plain","size":4847}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"test_output_dir::0","time":{"start":1724809468612,"stop":1724809468613,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"copy_config_to_dir::finish_callback","time":{"start":1724809468613,"stop":1724809468614,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"lib.youtube"},{"name":"suite","value":"test_y2_downloader"},{"name":"host","value":"fv-az1535-547"},{"name":"thread","value":"8987-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"lib.youtube.test_y2_downloader"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"url","value":"'https://www.youtube.com/watch?v=0AVrZ5tw_SM'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"27b666c6408c0bdb.json","parameterValues":["'https://www.youtube.com/watch?v=0AVrZ5tw_SM'"]}