{"uid":"bc5d030e199cdaca","name":"test_y2_downloader[video]","fullName":"lib.youtube.test_y2_downloader#test_y2_downloader","historyId":"d1a0b4889c40e956ba730446cbb448e5","time":{"start":1729603659285,"stop":1729603698683,"duration":39398},"description":"\n    测试 youtu 下载工具\n    ","descriptionHtml":"<pre><code>测试 youtu 下载工具\n</code></pre>\n","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7fb874023700 state=finished raised PytubeError>]","statusTrace":"self = <pytube.__main__.YouTube object: videoId=0AVrZ5tw_SM>\n\n    @property\n    def title(self) -> str:\n        \"\"\"Get the video title.\n    \n        :rtype: str\n        \"\"\"\n        if self._title:\n            return self._title\n    \n        try:\n>           self._title = self.vid_info['videoDetails']['title']\nE           KeyError: 'videoDetails'\n\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/pytube/__main__.py:341: KeyError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Retrying object at 0x7fb874023d00 (stop=<tenacity.stop.stop_after_attempt object at 0x7fb874cb2970>, wait=<tenacity.w...0x7fb8a6153ee0>, before=<function before_nothing at 0x7fb8a6151430>, after=<function after_nothing at 0x7fb8a6151790>)>\nfn = <function Y2Downloader.download_video at 0x7fb874c971f0>\nargs = (<mypy.lib.youtube.y2_downloader.Y2Downloader object at 0x7fb8740232b0>, 'https://www.youtube.com/watch?v=0AVrZ5tw_SM')\nkwargs = {}\nretry_state = <RetryCallState 140430197014000: attempt #5; slept for 36.0; last result: failed (PytubeError Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube)>\ndo = <tenacity.DoAttempt object at 0x7fb874023880>\n\n    def __call__(\n        self,\n        fn: t.Callable[..., WrappedFnReturnT],\n        *args: t.Any,\n        **kwargs: t.Any,\n    ) -> WrappedFnReturnT:\n        self.begin()\n    \n        retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)\n        while True:\n            do = self.iter(retry_state=retry_state)\n            if isinstance(do, DoAttempt):\n                try:\n>                   result = fn(*args, **kwargs)\n\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/tenacity/__init__.py:478: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/youtube/y2_downloader.py:183: in download_video\n    raise ex\nmypy/lib/youtube/y2_downloader.py:153: in download_video\n    api = Y2VideoHandler(work_path=self._work_path,\nmypy/lib/youtube/y2_video_handler.py:239: in __init__\n    self._video_original_title = y2_video.title\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pytube.__main__.YouTube object: videoId=0AVrZ5tw_SM>\n\n    @property\n    def title(self) -> str:\n        \"\"\"Get the video title.\n    \n        :rtype: str\n        \"\"\"\n        if self._title:\n            return self._title\n    \n        try:\n            self._title = self.vid_info['videoDetails']['title']\n        except KeyError:\n            # Check_availability will raise the correct exception in most cases\n            #  if it doesn't, ask for a report.\n            self.check_availability()\n>           raise exceptions.PytubeError(\n                (\n                    f'Exception while accessing title of {self.watch_url}. '\n                    'Please file a bug report at https://github.com/pytube/pytube'\n                )\n            )\nE           pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube\n\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/pytube/__main__.py:346: PytubeError\n\nThe above exception was the direct cause of the following exception:\n\ntest_output_dir = '/home/runner/work/github-runner/github-runner/mypy/tests/lib/youtube/_out/test_y2_downloader'\nurl = 'https://www.youtube.com/watch?v=0AVrZ5tw_SM'\n\n    @pytest.mark.parametrize(\"url\", [\n        \"https://www.youtube.com/watch?v=0AVrZ5tw_SM\",\n        \"https://www.youtube.com/playlist?list=PL-CDIidnoXnBqgBVbf5y9Qm4y4ZKHHYUS\",\n        \"https://www.youtube.com/channel/UC4cw8Y12uIvrh8eLwGA3n8A\"],\n        ids=['video', 'playlist', 'channel'])\n    def test_y2_downloader(test_output_dir, url):\n        \"\"\"\n        测试 youtu 下载工具\n        \"\"\"\n        api = Y2Downloader(work_path=test_output_dir, url=url)\n>       download_filepath = api.do_download()\n\nmypy/tests/lib/youtube/test_y2_downloader.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/youtube/y2_downloader.py:280: in do_download\n    download_filepath, _, _, _ = self.download_video(self._url)\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/tenacity/__init__.py:336: in wrapped_f\n    return copy(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/tenacity/__init__.py:475: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/tenacity/__init__.py:376: in iter\n    result = action(retry_state)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nrs = <RetryCallState 140430197014000: attempt #5; slept for 36.0; last result: failed (PytubeError Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube)>\n\n    def exc_check(rs: \"RetryCallState\") -> None:\n        fut = t.cast(Future, rs.outcome)\n        retry_exc = self.retry_error_cls(fut)\n        if self.reraise:\n            raise retry_exc.reraise()\n>       raise retry_exc from fut.exception()\nE       tenacity.RetryError: RetryError[<Future at 0x7fb874023700 state=finished raised PytubeError>]\n\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/tenacity/__init__.py:419: RetryError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop_policy","time":{"start":1729597033245,"stop":1729597033245,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"copy_config_to_dir","time":{"start":1729603659282,"stop":1729603659284,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"test_output_dir","time":{"start":1729603659284,"stop":1729603659284,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"\n    测试 youtu 下载工具\n    ","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7fb874023700 state=finished raised PytubeError>]","statusTrace":"self = <pytube.__main__.YouTube object: videoId=0AVrZ5tw_SM>\n\n    @property\n    def title(self) -> str:\n        \"\"\"Get the video title.\n    \n        :rtype: str\n        \"\"\"\n        if self._title:\n            return self._title\n    \n        try:\n>           self._title = self.vid_info['videoDetails']['title']\nE           KeyError: 'videoDetails'\n\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/pytube/__main__.py:341: KeyError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <Retrying object at 0x7fb874023d00 (stop=<tenacity.stop.stop_after_attempt object at 0x7fb874cb2970>, wait=<tenacity.w...0x7fb8a6153ee0>, before=<function before_nothing at 0x7fb8a6151430>, after=<function after_nothing at 0x7fb8a6151790>)>\nfn = <function Y2Downloader.download_video at 0x7fb874c971f0>\nargs = (<mypy.lib.youtube.y2_downloader.Y2Downloader object at 0x7fb8740232b0>, 'https://www.youtube.com/watch?v=0AVrZ5tw_SM')\nkwargs = {}\nretry_state = <RetryCallState 140430197014000: attempt #5; slept for 36.0; last result: failed (PytubeError Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube)>\ndo = <tenacity.DoAttempt object at 0x7fb874023880>\n\n    def __call__(\n        self,\n        fn: t.Callable[..., WrappedFnReturnT],\n        *args: t.Any,\n        **kwargs: t.Any,\n    ) -> WrappedFnReturnT:\n        self.begin()\n    \n        retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)\n        while True:\n            do = self.iter(retry_state=retry_state)\n            if isinstance(do, DoAttempt):\n                try:\n>                   result = fn(*args, **kwargs)\n\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/tenacity/__init__.py:478: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/youtube/y2_downloader.py:183: in download_video\n    raise ex\nmypy/lib/youtube/y2_downloader.py:153: in download_video\n    api = Y2VideoHandler(work_path=self._work_path,\nmypy/lib/youtube/y2_video_handler.py:239: in __init__\n    self._video_original_title = y2_video.title\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pytube.__main__.YouTube object: videoId=0AVrZ5tw_SM>\n\n    @property\n    def title(self) -> str:\n        \"\"\"Get the video title.\n    \n        :rtype: str\n        \"\"\"\n        if self._title:\n            return self._title\n    \n        try:\n            self._title = self.vid_info['videoDetails']['title']\n        except KeyError:\n            # Check_availability will raise the correct exception in most cases\n            #  if it doesn't, ask for a report.\n            self.check_availability()\n>           raise exceptions.PytubeError(\n                (\n                    f'Exception while accessing title of {self.watch_url}. '\n                    'Please file a bug report at https://github.com/pytube/pytube'\n                )\n            )\nE           pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube\n\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/pytube/__main__.py:346: PytubeError\n\nThe above exception was the direct cause of the following exception:\n\ntest_output_dir = '/home/runner/work/github-runner/github-runner/mypy/tests/lib/youtube/_out/test_y2_downloader'\nurl = 'https://www.youtube.com/watch?v=0AVrZ5tw_SM'\n\n    @pytest.mark.parametrize(\"url\", [\n        \"https://www.youtube.com/watch?v=0AVrZ5tw_SM\",\n        \"https://www.youtube.com/playlist?list=PL-CDIidnoXnBqgBVbf5y9Qm4y4ZKHHYUS\",\n        \"https://www.youtube.com/channel/UC4cw8Y12uIvrh8eLwGA3n8A\"],\n        ids=['video', 'playlist', 'channel'])\n    def test_y2_downloader(test_output_dir, url):\n        \"\"\"\n        测试 youtu 下载工具\n        \"\"\"\n        api = Y2Downloader(work_path=test_output_dir, url=url)\n>       download_filepath = api.do_download()\n\nmypy/tests/lib/youtube/test_y2_downloader.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmypy/lib/youtube/y2_downloader.py:280: in do_download\n    download_filepath, _, _, _ = self.download_video(self._url)\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/tenacity/__init__.py:336: in wrapped_f\n    return copy(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/tenacity/__init__.py:475: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/tenacity/__init__.py:376: in iter\n    result = action(retry_state)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nrs = <RetryCallState 140430197014000: attempt #5; slept for 36.0; last result: failed (PytubeError Exception while accessing title of https://youtube.com/watch?v=0AVrZ5tw_SM. Please file a bug report at https://github.com/pytube/pytube)>\n\n    def exc_check(rs: \"RetryCallState\") -> None:\n        fut = t.cast(Future, rs.outcome)\n        retry_exc = self.retry_error_cls(fut)\n        if self.reraise:\n            raise retry_exc.reraise()\n>       raise retry_exc from fut.exception()\nE       tenacity.RetryError: RetryError[<Future at 0x7fb874023700 state=finished raised PytubeError>]\n\n/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/tenacity/__init__.py:419: RetryError","steps":[],"attachments":[{"uid":"7c6a11ed82ecdce","name":"log","source":"7c6a11ed82ecdce.txt","type":"text/plain","size":8364}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"test_output_dir::0","time":{"start":1729603739332,"stop":1729603739332,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"copy_config_to_dir::finish_callback","time":{"start":1729603739333,"stop":1729603739333,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"lib.youtube"},{"name":"suite","value":"test_y2_downloader"},{"name":"host","value":"fv-az1391-672"},{"name":"thread","value":"9859-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"lib.youtube.test_y2_downloader"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"url","value":"'https://www.youtube.com/watch?v=0AVrZ5tw_SM'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"bc5d030e199cdaca.json","parameterValues":["'https://www.youtube.com/watch?v=0AVrZ5tw_SM'"]}